name: ecredis CI

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: erlang
        uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 23.2

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "6.2"
          auto-start: "false"

      - name: Checkout ecredis_crc16
        uses: actions/checkout@v2
        with:
            repository: HalloAppInc/ecredis-crc16
            token: ${{ secrets.nikola_github_secret }}
            path: deps/ecredis_crc16

      - name: Prepare Deps
        run: ./rebar prepare-deps

      - name: Compile
        run: ./rebar compile

      - name: Start Redis Cluster
        run: cd scripts; ./create-cluster start; echo yes | ./create-cluster create

      - name: Tests
        run: ./rebar eunit

      - name: Publish coverage report
        uses: actions/upload-artifact@v2
        with:
            name: coverage
            path: |
                .eunit/index.html
                .eunit/*.COVER.html

